# Generated by Django 5.2.11 on 2026-02-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('any', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personatges', to='animes.anime')),
            ],
        ),
    ]
